### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by kwikiel** [riccardomusmeci/mlx-llm#3]
python demo/llm_chat.py
Traceback (most recent call last):
  File "/Users/my_username/mlx-llm/mlx-llm/mlx-llm/demo/llm_chat.py", line 2, in <module>
    from mlx_llm.model import LLM
ModuleNotFoundError: No module named 'mlx_llm'

Steps to reproduce: 
git clone https://github.com/riccardomusmeci/mlx-llm
cd mlx-llm
pip install .

Using Mac OS X 14.2.1 with Python 3.12

**Comment by riccardomusmeci** [comment]
Use python 3.10 versions. Let me know if it works fine.

**Comment by hg7643** [comment]
try 

from mlx_llm.model.llm import LLM

**Comment by riccardomusmeci** [comment]
@kwikiel did it work?
